@startuml "Battleship protocol"
participant "peer (host)" as ph
participant "peer (client)" as pc

activate ph

ph -> ph : start hosting
activate ph

ph -> ph : create keys (pair, one time)
activate ph
deactivate ph

ph -> ph : randomize true/false
activate ph
deactivate ph

ph --> ph : wait for connection
deactivate ph

pc -> ph : connect
activate pc
ph -> pc : accept

pc -> pc : create keys (pair, one time)
activate pc
deactivate pc

pc -> pc : guess true/false
activate pc
deactivate pc

ph -> ph : create board
activate ph
pc -> pc : create board
activate pc

ph -> ph : encrypt board
activate ph
pc -> pc : encrypt board
activate pc

deactivate ph
deactivate pc
ph --> ph : wait for other
deactivate ph
pc --> pc : wait for other
deactivate pc

ph -> pc : send encrypted board
pc -> ph : send encrypted board
pc -> ph : send guess
ph -> ph : validate guess
activate ph
ph -> pc : send priority
deactivate ph

@enduml